/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiPublicMachineStatusRouteImport } from './routes/api/public/machine-status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMachineStatusRoute = ApiPublicMachineStatusRouteImport.update({
  id: '/api/public/machine-status',
  path: '/api/public/machine-status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/public/machine-status': typeof ApiPublicMachineStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/public/machine-status': typeof ApiPublicMachineStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/public/machine-status': typeof ApiPublicMachineStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/history' | '/api/public/machine-status'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/history' | '/api/public/machine-status'
  id: '__root__' | '/' | '/api/history' | '/api/public/machine-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiPublicMachineStatusRoute: typeof ApiPublicMachineStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/machine-status': {
      id: '/api/public/machine-status'
      path: '/api/public/machine-status'
      fullPath: '/api/public/machine-status'
      preLoaderRoute: typeof ApiPublicMachineStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiPublicMachineStatusRoute: ApiPublicMachineStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
